"""
Constantes para el juego Batalla Naval
Archivo para centralizar todos los valores constantes y eliminar números mágicos
"""

# === CONFIGURACIÓN DE RED ===
DEFAULT_SERVER_HOST = "localhost"
DEFAULT_SERVER_PORT = 8888
NETWORK_BUFFER_SIZE = 1024
NETWORK_TIMEOUT = 1.0

# === CONFIGURACIÓN DE VENTANA Y UI ===
# Ventana principal
MIN_WINDOW_WIDTH = 1200
MIN_WINDOW_HEIGHT = 800
INITIAL_WINDOW_WIDTH = 1200
INITIAL_WINDOW_HEIGHT = 800

# Configuración de FPS
TARGET_FPS = 60

# === CONFIGURACIÓN DE JUEGO ===
# Tablero de juego
GRID_SIZE = 10
BOARD_SIZE_DEFAULT = 450
CELL_MARGIN = 2

# Configuración de barcos
SHIP_SIZES = [5, 4, 3, 3, 2]
SHIP_NAMES = {
    5: "Portaaviones",
    4: "Destructor Acorazado", 
    3: "Barco de Ataque",
    2: "Lancha Rapida"
}

# Estados de celda
CELL_EMPTY = 0
CELL_SHIP = 1
CELL_HIT = 2
CELL_WATER_HIT = 3

# Máximo de jugadores
MAX_PLAYERS = 2

# === CONFIGURACIÓN DE UI ===
# Connection Dialog
CONNECTION_INPUT_WIDTH = 450
CONNECTION_INPUT_HEIGHT = 55
CONNECTION_BUTTON_WIDTH = 200
CONNECTION_BUTTON_HEIGHT = 55
MAX_HOST_LENGTH = 50
MAX_PORT_LENGTH = 5
CURSOR_BLINK_INTERVAL = 500

# Menu
MENU_BUTTON_WIDTH = 300
MENU_BUTTON_HEIGHT = 60
MUTE_BUTTON_WIDTH = 100
MUTE_BUTTON_HEIGHT = 40
MUTE_BUTTON_MARGIN = 20

# Game Over Screen
GAME_OVER_BUTTON_WIDTH = 200
GAME_OVER_BUTTON_HEIGHT = 60

# Fuentes
FONT_SIZE_LARGE = 96
FONT_SIZE_TITLE = 56
FONT_SIZE_BOARD_TITLE = 42
FONT_SIZE_DIALOG_TITLE = 48
FONT_SIZE_NORMAL = 32
FONT_SIZE_INFO = 28
FONT_SIZE_SMALL = 24
FONT_SIZE_COORD = 20

# Espaciado
PANEL_PADDING = 15
COORD_SPACE = 40
TITLE_SPACE = 80
BOARD_TITLE_SPACE = 60
INFO_SPACE = 150
BOARD_SPACING = 150
TITLE_SPACING = 15
WINDOW_MARGINS = 160

# === CONFIGURACIÓN DE AUDIO ===
# Volúmenes de audio
MUSIC_VOLUME_MENU = 0.3
MUSIC_VOLUME_GAME = 0.2
MISSILE_SOUND_VOLUME = 0.3
SPLASH_SOUND_VOLUME = 0.25
MUTED_VOLUME = 0.0

# Configuración del mixer
MIXER_FREQUENCY = 44100
MIXER_SIZE = -16
MIXER_CHANNELS = 2
MIXER_BUFFER = 1024

# === CONFIGURACIÓN DE COLORES ===
# Colores principales (RGB)
COLOR_OCEAN_START = (30, 60, 90)
COLOR_OCEAN_END = (70, 130, 200)
COLOR_WATER = (70, 130, 180)
COLOR_WATER_DARK = (50, 100, 150)
COLOR_SHIP = (101, 67, 33)
COLOR_HIT = (220, 20, 60)
COLOR_MISS = (255, 255, 255)
COLOR_GRID = (30, 60, 100)
COLOR_HOVER = (255, 255, 0, 100)

# Colores de UI
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_RED = (255, 0, 0)
COLOR_YELLOW = (255, 255, 0)

# Colores de botones
COLOR_BUTTON_CONNECT = (70, 130, 180)
COLOR_BUTTON_CONNECT_HOVER = (100, 149, 237)
COLOR_BUTTON_CONNECT_ACTIVE = (34, 139, 34)
COLOR_BUTTON_START = (34, 139, 34)
COLOR_BUTTON_START_HOVER = (50, 205, 50)
COLOR_BUTTON_DISABLED = (100, 100, 100)
COLOR_BUTTON_CANCEL = (180, 70, 70)
COLOR_BUTTON_CANCEL_HOVER = (220, 100, 100)
COLOR_BUTTON_MUTE = (70, 70, 70)
COLOR_BUTTON_MUTE_HOVER = (100, 100, 100)

# Colores de paneles
COLOR_PANEL_MY_BOARD = (20, 40, 60)
COLOR_PANEL_ENEMY_BOARD = (40, 20, 20)
COLOR_PANEL_INFO = (25, 45, 85)
COLOR_PANEL_MY_SHIPS = (20, 60, 40)
COLOR_PANEL_ENEMY_SHIPS = (60, 20, 20)

# Bordes de paneles
COLOR_BORDER_MY_BOARD = (100, 149, 237)
COLOR_BORDER_ENEMY_BOARD = (220, 20, 60)
COLOR_BORDER_INFO = (120, 160, 255)
COLOR_BORDER_MY_SHIPS = (100, 200, 120)
COLOR_BORDER_ENEMY_SHIPS = (200, 100, 100)

# Transparencias
PANEL_ALPHA = 100
PANEL_ALPHA_STRONG = 130
PANEL_ALPHA_INFO = 180
OVERLAY_ALPHA = 120
PREVIEW_ALPHA = 60
GAME_OVER_ALPHA = 180

# === CONFIGURACIÓN DE BARCOS REALISTAS ===
# Colores de barcos
SHIP_HULL_COLOR = (45, 55, 65)
SHIP_DECK_COLOR = (120, 100, 80)
SHIP_METAL_COLOR = (85, 85, 85)
SHIP_CANNON_COLOR = (40, 40, 40)
SHIP_DETAIL_COLOR = (200, 180, 140)
SHIP_WINDOW_COLOR = (100, 150, 200)
SHIP_RADAR_COLOR = (60, 60, 60)
SHIP_WATER_LINE_COLOR = (65, 75, 85)

# Efectos de impacto
EXPLOSION_COLORS = [
    (255, 0, 0),    # Rojo central
    (255, 100, 0),  # Naranja
    (255, 200, 0),  # Amarillo
    (255, 255, 100) # Amarillo claro
]

SPLASH_COLORS = [
    (100, 150, 255),  # Azul claro
    (150, 200, 255),  # Azul más claro
    (200, 230, 255)   # Azul muy claro
]

# Tamaños de misiles
MISSILE_SIZE_HIT = 3  # Factor de tamaño para misiles de impacto
MISSILE_SIZE_MISS = 4  # Factor de tamaño para misiles de fallo

# === CONFIGURACIÓN DE LAYOUT ===
# Ship Status Panels
SHIP_STATUS_PANEL_WIDTH = 200
SHIP_STATUS_PANEL_HEIGHT = 300
SHIP_STATUS_MARGIN = 10
SHIP_STATUS_Y_OFFSET_START = 40
SHIP_STATUS_Y_OFFSET_INCREMENT = 45

# Coordenadas del tablero
COORD_BG_MIN_WIDTH = 25
COORD_BG_MIN_HEIGHT = 20
COORD_BG_MARGIN = 8

# === ARCHIVOS DE RECURSOS ===
# Rutas de imágenes
IMAGE_MENU_PATH = "assets/images/menu.png"

# Rutas de sonidos
SOUND_BACKGROUND_MENU = "assets/sounds/piratas.mp3"
SOUND_BACKGROUND_GAME = "assets/sounds/background.mp3"
SOUND_MISSILE_HIT = "assets/sounds/misil.mp3"
SOUND_WATER_SPLASH = "assets/sounds/waterSplash.mp3"

# === CONFIGURACIÓN DE SERVIDOR ===
# Timeouts y límites
SERVER_READ_TIMEOUT = 1.0
SERVER_CLOSE_TIMEOUT = 5
JSON_DECODE_MAX_RETRIES = 3

# UUID
UUID_SHORT_LENGTH = 8

# === CONFIGURACIÓN DE MENSAJES ===
# Límites de caracteres para mensajes
MESSAGE_TYPE_MAX_LENGTH = 50
ERROR_MESSAGE_MAX_LENGTH = 200
PLAYER_ID_LENGTH = 8

# === CONFIGURACIÓN DE LOGGING ===
LOG_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'

# === CONFIGURACIÓN DE POSICIONES DE UI ===
# Posiciones de menú
MENU_BUTTON_Y_CONNECT = 400
MENU_BUTTON_Y_START = 500
MENU_STATUS_Y = 620

# Posiciones de juego
GAME_TITLE_Y = 35
GAME_INFO_Y_OFFSET = 75
GAME_STATUS_Y_OFFSET = 45

# === CONFIGURACIÓN DE VALIDACIÓN ===
# Límites de entrada
MIN_PORT_NUMBER = 1
MAX_PORT_NUMBER = 65535
MIN_COORDINATE = 0
MAX_COORDINATE = 9

# === CONFIGURACIÓN DE ESCALADO ===
# Factores de escalado para diferentes tamaños de ventana
BOARD_SIZE_SCALE_FACTOR = 0.8
MIN_COORD_FONT_SIZE = 20
MAX_COORD_FONT_SIZE = 32
COORD_FONT_CELL_RATIO = 2  # cell_size // 2

# === CONFIGURACIÓN DE TIEMPO ===
# Delays y timeouts
CONNECTION_CHECK_INTERVAL = 1.0
ANIMATION_FRAME_TIME = 16  # ~60 FPS

# === CONFIGURACIÓN DE DESARROLLO ===
# Flags de debug
DEBUG_NETWORK = False
DEBUG_GAME_STATE = False
DEBUG_UI = False